---
# Setup/install tasks.
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Ensure Java is installed.
  apt: "name={{ item }} state=installed"
  with_items: ['openjdk-7-jdk']
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Ensure Java is installed.
  yum: "name={{ item }} state=installed"
  with_items: ['java-1.7.0-openjdk']
  when: ansible_distribution == 'Suse' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: "Downloading Takipi for Debian/Ubuntu"
  get_url: 'url="https://app.takipi.com/app/download?t=deb&r=chef" dest="/tmp/takipi.deb"'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: "Downloading Takipi for RHEL/SUSE"
  get_url: 'url="https://app.takipi.com/app/download?t=rpm&r=chef" dest="/tmp/takipi.rpm"'
  when: ansible_distribution == 'Suse' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Installing Takipi for RHEL/SUSE
  yum: name=/tmp/takipi.rpm
  when: ansible_distribution == 'Suse' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Installing Takipi for Ubuntu/Debian
  apt: deb=/tmp/takipi.deb
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Run Takipi Setup Package
  shell: /opt/takipi/etc/takipi-setup-package #{{takipi.SECRET_KEY}}

- name: Stat /opt/takipi/work/secret.key to check if it exists
  stat: path=/opt/takipi/work/secret.key
  register: secret_key_file

- name: Check if test on installation failed
  fail: msg="Takipi failed to install. Takipi didn't recognise your OS or Did you forget to add a Takipi secret_key?"
  when: secret_key_file.stat.isfile is defined and not secret_key_file.stat.isfile
